In [1]:
#1. Create a rank 2 (2D) array that resembles the matrix below.
import numpy as np
array_2d = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])
print(array_2d)

[[11 12 13 14]
 [15 16 17 18]]


In [2]:
#1. Create an array with 4 rows and 3 columns of zeros.
zeros_array = np.zeros((4, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#2.Create an array of ones that has 3 rows and 4 columns.
ones_array = np.ones((3, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#3. Create an array containing integers 4 to 13 inclusive.
array_integers = np.arange(4, 14)
print(array_integers)

[ 4  5  6  7  8  9 10 11 12 13]


In [5]:
#4. Create an array containing [0., 1.5, 3., 4.5]
array_floats = np.array([0., 1.5, 3., 4.5])
print(array_floats)

[0.  1.5 3.  4.5]


In [6]:
#5. Create a 2 by 2 array containing '4' in each position.
array_4s = np.full((2, 2), 4)
print(array_4s)

[[4 4]
 [4 4]]


In [7]:
#6. Create 2 matrices:
#i. Identity matrix of size 4
#ii. Diagonal matrix with [10,12] as the diagonals
identity_matrix = np.eye(4)
print(identity_matrix)
diagonal_matrix = np.diag([10, 12])
print(diagonal_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0]
 [ 0 12]]


In [8]:
#7. Create a 3 by 3 array with random floats in [0, 10].
np.random.seed(0)
random_array = np.random.uniform(0, 10, size=(3, 3))
print(random_array)

[[5.48813504 7.15189366 6.02763376]
 [5.44883183 4.23654799 6.45894113]
 [4.37587211 8.91773001 9.63662761]]


In [9]:
#8. Create a 3 by 3 array with random integers in [10, 20].
np.random.seed(0)
random_int_array = np.random.randint(10, 21, size=(3, 3))
print(random_int_array)

[[15 10 13]
 [13 17 19]
 [13 15 12]]


In [10]:
#SLICING ARRAYS
#1. Use this array for the following practice:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# a. Get a subarray of the first row and first 2 columns
sub_array_a = myArray[0, :2]
print("Subarray of the first row and first 2 columns:")
print(sub_array_a)

# b. Change all elements in 1st and second row to 0
myArray[:2, :] = 0
print("\nArray after changing elements in the first and second rows to 0:")
print(myArray)


Subarray of the first row and first 2 columns:
[11 12]

Array after changing elements in the first and second rows to 0:
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


In [11]:
# Task 1: Create an array and reverse the order
array_task_1 = np.arange(21)[::-1]
print("Array with reversed order:")
print(array_task_1)

# Task 2: Reshape the array myArray to an array with 3 rows
myArray = np.array([[11, 12, 13], [14, 15, 16]])
reshaped_array = myArray.reshape(3, 2)
print("\nReshaped array with 3 rows:")
print(reshaped_array)

Array with reversed order:
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

Reshaped array with 3 rows:
[[11 12]
 [13 14]
 [15 16]]


In [12]:
#MATH 
#Use this array for the following practice: 
myArray = np.arange(10)

# 1. Find the square of every number in array
squared_array = np.square(myArray)
print("Square of every number in the array:")
print(squared_array)

# 2. Find the square root of every number in array
sqrt_array = np.sqrt(myArray)
print("\nSquare root of every number in the array:")
print(sqrt_array)

# 3. Multiply the square of each number in array with its respective square root
result_array = squared_array * sqrt_array
print("\nResult of multiplying the square of each number with its square root:")
print(result_array)

Square of every number in the array:
[ 0  1  4  9 16 25 36 49 64 81]

Square root of every number in the array:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

Result of multiplying the square of each number with its square root:
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [13]:
# Given array
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# 1. Add a new row of elements containing 20, 21, and 22
new_row = np.array([20, 21, 22])
myArray = np.vstack([myArray, new_row])

print("Array after adding a new row:")
print(myArray)

# 2. Add a new column of elements containing 30, 40, and 50
new_column = np.array([30, 40, 50])
myArray = np.hstack([myArray, new_column.reshape(-1, 1)])

print("\nArray after adding a new column:")
print(myArray)

Array after adding a new row:
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [14]:
# 1. Add 1 column of 1 to this array: myArray = np.zeros((2,2))
myArray = np.zeros((2, 2))
myArray = np.hstack((myArray, np.ones((2, 1))))

print("Array after adding 1 column of 1:")
print(myArray)

# 2. Add 2 rows of 2 to the answer from part 1
myArray = np.vstack((myArray, np.ones((2, 3))))

print("\nArray after adding 2 rows of 2:")
print(myArray)

# 3. Remove the last column
myArray = np.delete(myArray, -1, axis=1)

print("\nArray after removing the last column:")
print(myArray)

# 4. Remove the last row
myArray = np.delete(myArray, -1, axis=0)

print("\nArray after removing the last row:")
print(myArray)

Array after adding 1 column of 1:
[[0. 0. 1.]
 [0. 0. 1.]]

Array after adding 2 rows of 2:
[[0. 0. 1.]
 [0. 0. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array after removing the last column:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]

Array after removing the last row:
[[0. 0.]
 [0. 0.]
 [1. 1.]]


In [15]:
#Deleting Elements
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])

# Remove the middle column (index 1) along axis 1 (columns)
modified_array = np.delete(myArray, 1, axis=1)

print("Array after removing the middle column:")
print(modified_array)

Array after removing the middle column:
[[1 3]
 [4 6]
 [9 7]]


In [16]:
#TEST EXERCISE
# Exercise 1
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
modified_exercise_1 = np.where(exercise_1 % 2 != 0, -1, exercise_1)

print("Exercise 1 - Modified array:")
print(modified_exercise_1)

# Exercise 2
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
reshaped_exercise_2 = exercise_2.reshape(3, -1)

print("\nExercise 2 - Reshaped array:")
print(reshaped_exercise_2)

Exercise 1 - Modified array:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

Exercise 2 - Reshaped array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# Exercise 3
exercise_3 = np.arange(4).reshape(2, -1)

# Add 202 to all values in the array
modified_exercise_3 = exercise_3 + 202

print("Modified array after adding 202 to all values:")
print(modified_exercise_3)

Modified array after adding 202 to all values:
[[202 203]
 [204 205]]


In [18]:
# Generate a 1-D array of 10 random integers between 30 and 40 (inclusive)
random_integers = np.random.randint(30, 41, size=10)

print("Random integers between 30 and 40:")
print(random_integers)

Random integers between 30 and 40:
[34 37 36 38 38 40 31 36 37 37]


In [19]:
# Given arrays
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

# Find positions where the value in x is more than its corresponding element in y
more_positions = np.where(x > y)[0]

# Find positions where the value in x equals its corresponding element in y
equal_positions = np.where(x == y)[0]

print("Positions where the value in x is more than its corresponding element in y:")
print(more_positions)

print("\nPositions where the value in x equals its corresponding element in y:")
print(equal_positions)

Positions where the value in x is more than its corresponding element in y:
[1 2 4 5 6 7 8 9]

Positions where the value in x equals its corresponding element in y:
[0]


In [ ]:
#Extract the first four columns of this 2-D array
# Given array
exercise_6 = np.arange(100).reshape(5, -1)

# Extract the first four columns
first_four_columns = exercise_6[:, :4]

print("First four columns of the array:")
print(first_four_columns)